- docs-learnblocks/index.css
Should make visiting the docs a lot more gentle for first-time visitors. Thanks!
- __learnblocks__: remove reflow when first landing on the home page (non-cached).
> learnblocks: smooth out loading

- gulpfile.js
This will fix the non responsive feedback while building:
```
➜  docs git:(expand_api) ✗ make build
node_modules/.bin/gulp build
[16:38:54] Using gulpfile ~/dev/wercker/docs/gulpfile.js
[16:38:54] Starting 'docs'...
[16:38:54] Finished 'docs' after 434 ms
[16:38:54] Starting 'modules'...
[16:38:54] Finished 'modules' after 856 μs
[16:38:54] Starting 'styles'...
[16:38:54] Finished 'styles' after 2.19 ms
[16:38:54] Starting 'assets'...
[16:38:54] Finished 'assets' after 2.13 ms
[16:38:54] Starting 'fonts'...
[16:38:54] Finished 'fonts' after 2.05 ms
[16:38:54] Starting 'build'...
[16:38:54] Finished 'build' after 6.44 μs
```
After the `build` it will pause for 20-30 seconds.
> Return stream to show progress

- docs-sidebar/index.js
this allows a sidebar section to be an overview page (instead of the first article in the order).
> enable header sections to have an index.html / overview page

- content/api/endpoints/index.md
- content/api/getting-started/index.md
When clicking on a header it currently 404's, so added a index.md and some basic content. 
Fixes https://github.com/wercker/docs/issues/184
> Fix api headers in toc

- content/api/index.html
- content/docs/containers/dockerhub.md
- content/docs/containers/private-containers.md
- content/docs/index.html
- content/error/index.html
- legacy-urls/urlmappings.txt
Also redirect some legacy URL's to new devcenter articles (instead of redirecting to the old devcenter)
> Fix more broken links

- content/docs/containers/pushing-containers.md
For the pushing-containers article (also added is a mention of the `docker-scratch-push` step).
> Adds links to internal-steps docs

- content/docs/containers/pushing-containers.md
The `gcloud docker` commands were slightly changed in the latest versions of the Google Cloud SDK.
> Update GCR auth commands

- content/quickstarts/deployment/heroku.md
Make it clear that the environment variable used for `app-name` should not be prefixed with a `$` unlike the other variables, as defined here: https://github.com/wercker/step-heroku-deploy
> Update heroku.md key-name env var instructions

- content/docs/containers/pushing-containers.md
This PR removes one excess right square bracket `]` to correct Markdown link syntax.
> Remove excess right square bracket "]" from link

- content/learn/basics/the-wercker-cli.md
docker has deprecated the `boot2docker` tool in favor of docker machine. this changes the quick start docs to use docker machine to set up a docker environment
> instructions on using docker machine

- content/docs/using-the-cli/requirements.md
Changed the [requirements](http://devcenter.wercker.com/docs/using-the-cli/requirements.html) section of the `wercker cli` to use `docker-machine` rather than `boot2docker` since it has been deprecated.
> switched docs from boot2docker to docker-machine

- content/quickstarts/building/golang.md
- fixed a link to the proper docker container pulled from docker hub
- `boot2docker` is deprecated, uses `docker-machine` in place of it
> minor fixes in golang tutorial

- content/quickstarts/building/javascript.md
-fixes `rm ` command so that it works 
-links to proper container from docker hub
- adds highlighting around boot2docker
> minor patches for js tutorial

- content/docs/steps/creating-steps.md
It's hard to find a direct link to the step registry - the docs bounce back and forward between docs and learn pages. I found it via google, but this is where I would expect the link to be.
> Direct link to step registry.

- content/quickstarts/building/golang.md
- content/quickstarts/building/javascript.md
- content/quickstarts/building/ruby.md
http://devcenter.wercker.com/docs/steps/internal-steps.html#internal-watch
I should've done an ack-grep when I made https://github.com/wercker/docs/pull/368
> step "internal-watch" is actually "internal/watch"

- content/docs/steps/internal-steps.md
the behavior of docker push changed with these commits https://github.com/wercker/wercker/commit/024cd1c0bed66392219cd24f32ce5e0db986418c
https://github.com/wercker/wercker/commit/74c3400a4176ce435aa69a8ec7b2d3c09e73637a
to allow for (respectively):
- space or comma separated env tags or labels
- added a default tag (the build id) and a `force-tags` option
> adds new options for docker push

- docs-articles/index.css
Hard to reproduce, but sometimes bullet points are rendered weird. Possibly due to s3 returning content-type headers without an encoding. Using utf8 escape codes in the :before content fixes it.
> Use unicode escape for bullet points.

- content/api/index.md
Based on the discussions with @hatchan and @davegri 
```json
{
"message": "<message that is safe to show to the user>",
"code": "<unique error code>"
}
```
for instance:
```json
{
"message": "Your card was declined.",
"code": "stripe_card_declined"
}
```
> add information about error code

- content/api/endpoints/runs.md
pipelineId is (already marked as required)
> API docs: applicationId is not required for create-run

- content/docs/languages/golang.md
https://hub.docker.com/r/google/golang/ is deprecated by Google.
It's also creating troubles since this older image does not enable `GO15VENDOREXPERIMENT` which is now the default.
Also note `- golint` directive does not work correctly since it check code inside `vendor`.
> Doc pointing to an obsolete Go image

- content/docs/environment-variables/creating-env-vars.md
- content/docs/environment-variables/index.md
- content/docs/ssh-keys/generating-ssh-keys.md
- content/docs/ssh-keys/using-ssh-keys.md
We had some old naming regarding workflows in the docs, this clears that up.
- Clarifies how environment variables are overridden
- Clarifies the use of ssh keys
- Various small typos and fixes
> clarify different level envvars & ssh keys
