wercker.yml
This will add cache (when implemented in sentcli) and retries
=> Use npm-install

content/docs/index.md
- __content__: make GitHub the preferred location for opening up issues
=> content-docs: make GH the preferred entry point for contact

content/api/endpoints/deploys.md
- __content-api__: add deploys
- [wercker-models/deploy](https://github.com/wercker/wercker/blob/7dcc0c01a5b945e87e5c6daaa53d47f4e9da47b7/src/models/deploy.js)
=> content-api: add deploys

content/api/endpoints/applications.md
- __content-api__: add applications
- [api-applications/index.js](https://github.com/wercker/wercker/blob/b386b6e8317ae248a210000c4bc1468edb7a5a77/src/local_modules/api-applications/index.js)
- [api-applications/readme.md](https://github.com/wercker/wercker/blob/b386b6e8317ae248a210000c4bc1468edb7a5a77/src/local_modules/api-applications/README.md)
=> content-api: add applications

content/docs/index.html, content/error/index.html, content/index/index.html, content/learn/index.html, docs-metrics/index.js
These are the first steps towards creating a normalized template for the new build system, rather than having 5 different templates with lots of duplication. Moving this out of the template also improves maintainability. Thanks!
- __metrics__: add google analytics initialization
- __metrics__: add keen initialization
- __html__: fixed script declaration locus bug
=> metrics: dedupe

docs-nav/index.js
Hide the header for now. 
Will be reverted next week, when we release.
=> Hide API header

docs-nav/index.js, legacy-urls/urlmappings.txt
Closes #82. Depends on #159 to be merged first because of the new url's. Thanks!
- 8b86917 __docs-nav__: remove clickjacking behavior
=> docs-nav: rm clickjack behavior

content/docs/desktop-app/download.md
Hi,
Just fixing a small mistake here.
=> fix typo double 'a'

docs-metrics/index.js, docs-sidebar/toc-docs.json
closes #180
- __sidebar__: fix `json` bug
- __metrics__: fix keen bug
=> docs: fix lint bugs

content/docs/git/index.md, content/learn/index.html, docs-sidebar/toc-docs.json
Related: https://twitter.com/burhan/status/607998778377781248
=> Fix broken links in footer

content/docs/using-the-cli/installing.md
=> Update broken link

content/docs/faq/how-do-webhooks-work.md
=> Fix Typos/Grammar, Minor Clarification

content/api/endpoints/applications.md, docs-api/index.css
Adds querystring values for "list user application", "list builds by application", "list deploys by application".
=> Add querystring values

content/api/index.html, content/docs/index.html, docs-api/index.css, docs-articles/index.css, docs-sidebar/index.css, docs-sidebar/index.js, docs-sidebar/search.css, docs-sidebar/search.js
=> improves sidebar behaviour

content/api/index.html, content/docs/containers/pushing-containers.md, content/docs/deploy/index.md, content/docs/index.html, content/docs/pipelines/stacks.md, content/docs/services/index.md, content/docs/steps/index.md, content/docs/using-the-cli/introspecting-containers.md, content/error/index.html, content/learn/basics/the-wercker-cli.md, content/learn/index.html, legacy-urls/urlmappings.txt
Found these errors using the following wget command:
```
wget --spider  -o wget.log  -e robots=off --wait 1 -r -p http://devcenter.wercker.com
```
=> Fix multiple broken links

content/docs/environment-variables/deploy-variables.md, content/docs/steps/deploy-env-vars.md, docs-sidebar/toc-docs.json
Content already exists at: /docs/environment-variables/available-env-vars.html
=> removed deploy-variables article.

content/docs/web-interface/index.md
=> adds webinterface index

content/docs/deploy/index.md, content/docs/deploy/steps.md, content/docs/deploy/targets.md, docs-sidebar/toc-docs.json
It may look like the text for the index has been complete removed, however it's just moved to steps.md
=> add deploy/targets

content/api/index.html, content/docs/git/submodules.md, content/docs/index.html, content/error/index.html, content/index/index.html, content/learn/index.html, content/quickstarts/index.html, docs-badge-wip/index.css, docs-quicklinks/index.css, docs-quicklinks/index.js, index.js
=> Irc callout

content/docs/about.md, content/docs/about/index.md, content/docs/index.md, content/docs/steps/creating-steps.md, docs-sidebar/toc-docs.json
Provides a high-level overview of what wercker does and also a list of terminologies used throughout the docs.
Also a minor (style) fix to index.md
=> Add About wercker

docs-sidebar/index.css, docs-sidebar/index.js, docs-sidebar/list-learn.js
* generate proper html
* fix browser search bug
=> sidebar changes:

content/docs/environment-variables/after-step-variables.md, docs-bread-crumb/index.css, docs-bread-crumb/index.js, docs-toc-menu/index.css, docs-toc-menu/index.js
tried to fix ios bugs, do think the menu buttons works but probably needs a double tap
=> After step vars

content/docs/steps/script-step.md, docs-sidebar/toc-docs.json
=> Script step

content/docs/steps/index.md, content/docs/wercker-yml/yaml-syntax.md, docs-sidebar/toc-docs.json
Could really need some help and suggestions on this one.
What are the things we can tell and warn about....
=> Adds article on yml syntax

content/docs/pipelines/wercker-cache.md
=> Update for ewok caching

content/docs/containers/entrypoint.md, docs-sidebar/toc-docs.json
This should only be released after wercker/sentcli#520 is merged
=> Add entrypoint article

content/docs/containers/pushing-containers.md, content/docs/steps/internal-steps.md
Add section about the ports, and its notation (also fix typo)
=> Add ports section

content/docs/deploy/amazon-ecs.md
=> Normalize wercker.yml code snippets

content/docs/faq/alpine-faq.md, content/docs/faq/index.md, docs-sidebar/toc-docs.json
This just adds the article, still needs to be added to ToC somewhere
=> Add article about alpine

content/docs/web-interface/application-settings.md
and also rearanges the order of subjects
=> add info on ignored branches

content/api/endpoints/applications.md, content/api/endpoints/builds.md, content/api/endpoints/deploys.md, content/api/getting-started/authentication.md, content/api/index.md
Depends on wercker/wercker#1140
=> Add update an application section

README.md, package.json, wercker.yml
The dev steps will be focused on content editing. So they will only rebuild the content (which is way faster)
=> Add wercker dev pipeline

content/docs/steps/internal-steps.md
- descriptions taken from official docker docs: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/
=> adds support for the 4 new options for push

content/docs/ssh-keys/using-ssh-keys.md
the sections had opposite descriptions, switched em
=> fix egregiously incorrect sections

content/learn/pipelines/available-pipelines.md
=> update deploy section with new yml

content/quickstarts/building/python.md
http://devcenter.wercker.com/docs/steps/internal-steps.html#internal-watch
=> step "internal-watch" is actually "internal/watch"

content/cli/configuration/options-and-flags.md
how does the gitignore flag work? when's it enabled or disabled? let this magic documentation tell you the answers to all of that!!!!!!
=> Documents enable gitignore flag

content/quickstarts/building/javascript.md
=> Changed the image to node:4.2.6-slim

content/docs/steps/creating-steps.md
gonna use this to deeplink from the new empty state for a "step application"
=> add anchors to create steps article

content/docs/steps/internal-steps.md
thanks @stvnwrgs from https://github.com/wercker/wercker/issues/160#issuecomment-218547863
see also
* https://github.com/fsnotify/fsnotify/issues/129
* https://github.com/howeyc/fsnotify/issues/35
* https://github.com/fsnotify/fsnotify/wiki/FAQ
=> document raising open file limits.

content/docs/services/index.md
Depends on https://github.com/wercker/wercker/pull/103
=> named services

content/docs/containers/pushing-containers.md, content/docs/steps/internal-steps.md
Add docs on how to push to a v2 registry
=> Registry v2 docs

content/docs/steps/internal-steps.md
Also gets rid of force tags, because docker doesnt use them anymore
=> reflects that list values aren't in arrays

content/docs/index.html, docs-articles/index.css, docs-sidebar/index.js, docs-sidebar/search.css
This branch replaces the default sidebar search with Algolia Docsearch. Help by @davegri.
@lindseybateman does this visually look acceptable to you? Do you have any adjustments you'd like to make?
=> Change the documentation search to use Algolia Docsearch

content/docs/containers/private-containers.md
Pulling from GCR's example is wrong.
This description is that of when pushing GCR. 
So I was Fixed.
=> fix pulling from GCR example

content/docs/containers/multiple-tags.md, docs-sidebar/toc-docs.json
article on pushing multiple tags for containers
=> Push multiple tags
